export const personalInfoKey = "PERSONAL_FORMIK_VALUES"
export const experienceKey = "EXPERIENCE_FORMIK_VALUES"
export const educationKey = "EDUCATION_FORMIK_VALUES"
export const degreeOptionsKey = "DEGREE_OPTIONS"
export const experienceFormsIdArrKey = "EXPERIENCE_FORMS_ARR"
export const educationFormsIdArrKey = "EXPERIENCE_FORMS_ARR"